<?php
/**
 * Implements hook_theme().
 */
function first_module_theme($existing, $type, $theme, $path) {
  return [
    'first_template' => [
      'variables' => ['test_var' => NULL,'check'=>[]],
      'template' => 'first_template',
    ],
    'web_template' => [
      'variables' => ['test_var' => NULL],
      'template' => 'ogani_theme',
    ],
    'fetchData_template' => [
      'variables' => ['test_var' => NULL,'results'=>[]],
      'template' => 'fetch_data',
    ],
     'node_template' => [
      'variables' => ['test_var' => NULL,'artists'=>[]],
      'template' => 'node_data',
    ],
  ];
}

//Page Attachment Hook

function first_module_page_attachments(array &$attachments) {

  
  // Attach the CSS library to every page on the site.
  $attachments['#attached']['library'][] = 'first_module/first_module.styles';
 


}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function first_module_preprocess(&$variables) {

 $variables['module_base_path'] = file_create_url(drupal_get_path('module', 'first_module') . '/images/');

}

