<?php

/**
 * Implements hook_theme().
 */
function service_module_theme($existing, $type, $theme, $path) {
    
  return [
    'apiData_template' => [
      'variables' => ['test_var' => NULL,'results'=>[]],
      'template' => 'apiList_template',
    ],   
    
     'event_list_template' => [
      'variables' => ['test_var' => NULL,'data'=>[]],
      'template' => 'event_list_template',
    ],
  ];
}
